### ISSUE TITLE
select_subclasses doesn't interact well with .dates()

### ISSUE THREAD

**Issue by gavinwahl** [charettes/django-polymodels#22]
```python
class Base(PolymorphicModel):
    date = models.DateField()

class Child1(Base):
    pass

Child1.objects.select_subclasses(Child1).dates('date', 'month')
```

Throws this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "django/db/models/query.py", line 234, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "polymodels/managers.py", line 52, in iterator
    yield obj.type_cast()
AttributeError: 'datetime.date' object has no attribute 'type_cast'
```

I'm using select_subclasses as a way to add a filter on the content type as suggested in #21.

**Comment by charettes** [comment]
Will look into this.

**Comment by charettes** [comment]
Can you confirm #23 fixes your issue?

**Comment by gavinwahl** [comment]
It does, thanks
