### ISSUE TITLE
Can't install from source without django already installed

### ISSUE THREAD

**Issue by gavinwahl** [charettes/django-polymodels#25]
~~~
~/django-polymodels$ pip install -e .
Obtaining file:///home/gavin/django-polymodels
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/gavin/django-polymodels/setup.py", line 4, in <module>
        from polymodels import __version__
      File "polymodels/__init__.py", line 3, in <module>
        from django.utils.version import get_version
    ImportError: No module named django.utils.version
~~~

**Comment by charettes** [comment]
I'm aware of that, if you can come up with a solution that doesn't involve vendoring `django.utils.version` please share it. See c8a0daaea40bc8ff93e8e47dd80f524bdd0c38c6.

**Comment by gavinwahl** [comment]
Ok, I can work around it by not installing from source. Can you make a release with #23 and #20?

Thanks

**Comment by charettes** [comment]
Just release [1.4.2](https://pypi.python.org/pypi/django-polymodels/1.4.2).

**Comment by gavinwahl** [comment]
Thanks
