### ISSUE TITLE
Calling `.type_cast` sometimes raises `RelatedObjectDoesNotExist`

### ISSUE THREAD

**Issue by filipweidemann** [charettes/django-polymodels#47]
Sometimes, until the Django application is restarted, calling `.type_cast` on a base model raises `RelatedObjectDoesNotExist`. 

Here's the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/app/webpublisher/views.py", line 181, in get
    "fields": layout.fetch(code, current_lang=current_lang),
  File "/opt/app/core_storage/models.py", line 527, in fetch
    layout_element.type_cast().render(lysis, output, current_lang=current_lang)
  File "/usr/local/lib/python3.7/dist-packages/polymodels/models.py", line 112, in type_cast
    return accessor(self, with_prefetched_objects)
  File "/usr/local/lib/python3.7/dist-packages/polymodels/models.py", line 33, in __call__
    casted = self.attrgetter(obj)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/related_descriptors.py", line 415, in __get__
    self.related.get_accessor_name()
core_storage.models.BaseLayoutElement.titlelayoutelement.RelatedObjectDoesNotExist: BaseLayoutElement has no titlelayoutelement.
```

If there is anything else needed to investigate the issue, let me know please.
Thank you.

**Comment by charettes** [comment]
Are you using [`.delete(keep_parents=False)`](https://docs.djangoproject.com/en/2.2/ref/models/instances/#django.db.models.Model.delete) by any chance?

If it's not the case I'm afraid you'll have to provide a reduced test case to reproduce.

**Comment by filipweidemann** [comment]
We don't, but we're confident that this problem had something to do with an uwsgi configuration. It has not happened since. I'll close this issue for now, thank you for the fast response time!
